### ISSUE TITLE
Great results

### ISSUE THREAD

**Issue by ariel415el** [filipbasara0/simple-diffusion#5]
Thank you for uploading this project, 
 I was able  to train it on 1K FFHQ images for only one hour on a single 3060TI and good pretty nice images
 
![gs_21501](https://github.com/user-attachments/assets/783e5d89-301c-44cc-9c97-2bbfbae2e6e8)

**Comment by filipbasara0** [comment]
Wow, great job! That looks very good considering the size of the dataset and the training duration!

Thanks for sharing!
